# Generated by Django 4.2.3 on 2023-08-01 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname_en', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname_en', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField()),
                ('bio', tinymce.models.HTMLField(max_length=5000, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('color_uz', models.CharField(max_length=50)),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to='car_images/uz/')),
                ('name_ru', models.CharField(max_length=255)),
                ('color_ru', models.CharField(max_length=50)),
                ('image_ru', models.ImageField(upload_to='car_images/ru/')),
                ('name_en', models.CharField(max_length=255)),
                ('color_en', models.CharField(max_length=50)),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='car_images/en/')),
                ('car_number', models.CharField(default='00x000yy ab', max_length=50)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_created_by', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='myapp.driver')),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
