# Generated by Django 4.2.3 on 2023-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='images/en/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_ru',
            field=models.ImageField(default=None, upload_to='images/ru/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='images/uz/'),
        ),
    ]
